language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Squeak-5.2
  - Squeak-trunk
  
matrix:
  allow_failures:
    - smalltalk: Squeak-trunk
